version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-crypto-warehouse
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lynxrufus
      - MONGO_INITDB_ROOT_PASSWORD=atmylynxrufusserver

  mongo-express:
    image: mongo-express
    container_name: mongo-express-crypto-warehouse
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=lynxrufus
      - ME_CONFIG_MONGODB_ADMINPASSWORD=atmylynxrufusserver
      - ME_CONFIG_MONGODB_URL=mongodb://lynxrufus:atmylynxrufusserver@mongo:27017/

  node-crypto-warehouse:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node-crypto-warehouse
    restart: always
    environment:
      - MONGO_URL=mongodb://lynxrufus:atmylynxrufusserver@mongo:27017/
      - MONGO_DB_NAME=cryptoWarehouse
      - STAGE=PROD